# Numpy Examples

## 1) Computation with arrays

### a) Sigmoid activation function of a vector

In [1]:
import numpy as np
x = np.array([4, -1, 7, 9, 3, -5])

C:\Users\jacop\miniconda3\envs\dslab\lib\site-packages\ipykernel\parentpoller.py:110: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  warnings.warn(


**Apply the Sigmoid activation function: $y = sigmoid(x)$**
$$sigmoid(x_i) = \frac{1}{1+exp(-x_i)}$$
<img src='./sigmoid.png' width='40%'>

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(x)

array([0.98201379, 0.26894142, 0.99908895, 0.99987661, 0.95257413,
       0.00669285])

### b) Softmax activation function

Activation function that normalizes the input vector (z) to a discrete probability distribution (values of the result add to 1).

$$y_i = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [3]:
def SoftMax(x):
    return np.exp(x)/np.sum(np.exp(x))
#uguale a 
np.exp(x[0])/np.sum(np.exp(x))

0.005886735552643246

In [4]:
SoftMax(x)

array([5.88673555e-03, 3.96645122e-05, 1.18238244e-01, 8.73669020e-01,
       2.16560899e-03, 7.26480881e-07])

## 2) Broadcasting: dataset normalization

In [5]:
# Input table
n_samples = 100
n_columns = 5
mean = 1
std = 3
X = np.random.normal(mean, std, (n_samples, n_columns))

**Apply z-score: normalize each column by subtracting its mean and dividing by its standard deviation**

In [6]:
def zNormColumnWise(x):
    meanCol = x.mean(axis=0)
    stdCol = x.std(axis=0)
    return (x-meanCol)/stdCol

In [7]:
Xnorm = zNormColumnWise(X)

In [8]:
#Blocco di test
x = np.array([[6,3,7],[2,10,9]])
print(x.shape)
print(x)
y = np.array([2,5,1])
print(y.shape)
print(y)
print("x-y")
print(x-y)
print("x/y")
print(x/y)

(2, 3)
[[ 6  3  7]
 [ 2 10  9]]
(3,)
[2 5 1]
x-y
[[ 4 -2  6]
 [ 0  5  8]]
x/y
[[3.  0.6 7. ]
 [1.  2.  9. ]]


## 3) Accessing Numpy Arrays

In [10]:
#Input data
import numpy as np

# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1.4, 0.2],
           [4.3, 3. , 1.1, 0.1],
           [5. , 3.4, 1.6, 0.4],
           [5.1, 3.4, 1.5, 0.2],
           [6.9, 3.1, 4.9, 1.5],
           [6.7, 3.1, 4.4, 1.4],
           [6. , 2.9, 4.5, 1.5],
           [6.1, 3. , 4.6, 1.4],
           [6.5, 3. , 5.8, 2.2],
           [7.7, 3.8, 6.7, 2.2],
           [7.4, 2.8, 6.1, 1.9],
           [6.8, 3.2, 5.9, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2])

In [18]:
# Get column indices
height_i = columns.index('height')
intensity_i = columns.index('intensity')

**Compute the average height:**

In [20]:
avg_height = X[:,height_i].mean()
avg_height

6.133333333333334

**Compute the average height of samples with intensity greater than 5:**

In [23]:
X[:,height_i][X[:,intensity_i]>5].mean()

7.1000000000000005

**Compute the probability of class 2 if intensity>5**
$$p = \frac{\#(intensity>5 \land class2)}{\#(intensity>5)}$$

In [33]:
den = len(X[X[:,intensity_i]>5])
#oppure (dato che True ha valore 1 basta sommare per ottenere quanti True ci sono)
#den = X[X[:,intensity_i]>5].sum()

condG5 = X[:,intensity_i]>5
condC2 = labels == 2
num = len(X[condG5 & condC2])
#oppure
#num = X[condG5 & condC2].sum()

p = num/den
print("p: ", p)

p:  0.75


**Print the height of the top 3 records with highest intensity:**

In [34]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.4, 1.5, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [6.7, 3.1, 4.4, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 3. , 5.8, 2.2],
       [7.7, 3.8, 6.7, 2.2],
       [7.4, 2.8, 6.1, 1.9],
       [6.8, 3.2, 5.9, 2.3]])

In [42]:
#indici dei valori ordinati in modo crescente per colonna, sulla colonna intensity_i
print(np.argsort(X,axis=0)[:,intensity_i])

#prendiamo gli indici degli ultimi 3 valori (i 3 più grandi)
print(np.argsort(X,axis=0)[:,intensity_i][-3:])

#usiamo gli indici solo sulla colonna height_i
print(X[np.argsort(X,axis=0)[:, intensity_i][-3:], height_i])

[ 1  0  3  2  5  6  7  4  8 11 10  9]
[11 10  9]
[6.8 7.4 7.7]
